/**
 * Traduction des caracteristiques techniques.
 *
 * Les libelles se traduisent tous ; les valeurs seulement lorsqu'elles portent
 * du francais. « 6.8" AMOLED 120 Hz » se lit de la meme facon dans les trois
 * langues : la traduire n'apporterait rien et risquerait d'introduire une
 * erreur technique.
 */
export const labels = {
  Appairage: { en: "Pairing", ar: "الاقتران" },
  Audio: { en: "Audio", ar: "الصوت" },
  Autofocus: { en: "Autofocus", ar: "التركيز التلقائي" },
  Autonomie: { en: "Battery life", ar: "عمر البطارية" },
  Batterie: { en: "Battery", ar: "البطارية" },
  Boitier: { en: "Case", ar: "الهيكل" },
  Bus: { en: "Bus", ar: "الناقل" },
  Camera: { en: "Camera", ar: "الكاميرا" },
  "Camera avant": { en: "Front camera", ar: "الكاميرا الأمامية" },
  Capteur: { en: "Sensor", ar: "المستشعر" },
  Capteurs: { en: "Sensors", ar: "المستشعرات" },
  Codecs: { en: "Codecs", ar: "المرمّزات" },
  "Coeurs CUDA": { en: "CUDA cores", ar: "نوى CUDA" },
  Compatibilite: { en: "Compatibility", ar: "التوافق" },
  Connecteur: { en: "Connector", ar: "الموصّل" },
  Connectique: { en: "Connectivity", ar: "المنافذ" },
  Connexion: { en: "Connection", ar: "الاتصال" },
  Contraste: { en: "Contrast", ar: "التباين" },
  Couleurs: { en: "Colours", ar: "الألوان" },
  Courbure: { en: "Curvature", ar: "الانحناء" },
  DLSS: { en: "DLSS", ar: "DLSS" },
  Dalle: { en: "Panel", ar: "اللوحة" },
  Definition: { en: "Resolution", ar: "الدقة" },
  Dock: { en: "Dock", ar: "القاعدة" },
  Ecran: { en: "Display", ar: "الشاشة" },
  "Ecran externe": { en: "Outer display", ar: "الشاشة الخارجية" },
  "Ecran interne": { en: "Inner display", ar: "الشاشة الداخلية" },
  Epaisseur: { en: "Thickness", ar: "السماكة" },
  Ergonomie: { en: "Ergonomics", ar: "الأريحية" },
  Etancheite: { en: "Water resistance", ar: "مقاومة الماء" },
  Evitement: { en: "Obstacle avoidance", ar: "تفادي العوائق" },
  Fixation: { en: "Mount", ar: "التثبيت" },
  Fonction: { en: "Feature", ar: "الوظيفة" },
  Fonctions: { en: "Features", ar: "الوظائف" },
  Graphique: { en: "Graphics", ar: "الرسوميات" },
  HDR: { en: "HDR", ar: "HDR" },
  Hub: { en: "Hub", ar: "الموزّع" },
  Lecteur: { en: "Drive", ar: "المشغّل" },
  Luminosite: { en: "Brightness", ar: "السطوع" },
  Manette: { en: "Controller", ar: "وحدة التحكّم" },
  Memoire: { en: "Memory", ar: "الذاكرة" },
  Modes: { en: "Modes", ar: "الأوضاع" },
  Navigation: { en: "Navigation", ar: "التنقّل" },
  Plongee: { en: "Diving", ar: "الغوص" },
  Poids: { en: "Weight", ar: "الوزن" },
  Processeur: { en: "Processor", ar: "المعالج" },
  Puce: { en: "Chip", ar: "الشريحة" },
  Puissance: { en: "Power", ar: "القدرة" },
  RAM: { en: "RAM", ar: "الذاكرة العشوائية" },
  Rafraichissement: { en: "Refresh rate", ar: "معدّل التحديث" },
  "Reduction de bruit": { en: "Noise cancellation", ar: "عزل الضجيج" },
  Reseau: { en: "Network", ar: "الشبكة" },
  Resistance: { en: "Durability", ar: "المتانة" },
  Resolution: { en: "Resolution", ar: "الدقة" },
  "Resolution cible": { en: "Target resolution", ar: "الدقة المستهدفة" },
  Retour: { en: "Feedback", ar: "الاستجابة" },
  Retrocompatibilite: { en: "Backward compatibility", ar: "التوافقية الخلفية" },
  Retroeclairage: { en: "Backlight", ar: "الإضاءة الخلفية" },
  Securite: { en: "Security", ar: "الأمان" },
  Sorties: { en: "Outputs", ar: "المخارج" },
  Stabilisation: { en: "Stabilisation", ar: "التثبيت" },
  Stockage: { en: "Storage", ar: "السعة التخزينية" },
  Stylet: { en: "Stylus", ar: "القلم" },
  Suivi: { en: "Tracking", ar: "التتبّع" },
  Switches: { en: "Switches", ar: "المفاتيح" },
  Synchronisation: { en: "Synchronisation", ar: "المزامنة" },
  Systeme: { en: "System", ar: "النظام" },
  TDP: { en: "TDP", ar: "قدرة التصميم الحراري" },
  "Temps de reponse": { en: "Response time", ar: "زمن الاستجابة" },
  Transmission: { en: "Transmission", ar: "الإرسال" },
  Type: { en: "Type", ar: "النوع" },
  Video: { en: "Video", ar: "الفيديو" },
};

/** Seules les valeurs porteuses de francais figurent ici. */
export const values = {
  "Jusqu'a 29 h de video": { en: "Up to 29 h of video", ar: "حتى 29 ساعة فيديو" },
  "Jusqu'a 20 h de video": { en: "Up to 20 h of video", ar: "حتى 20 ساعة فيديو" },
  "Jusqu'a 19 h de video": { en: "Up to 19 h of video", ar: "حتى 19 ساعة فيديو" },
  "Jusqu'a 18 h": { en: "Up to 18 h", ar: "حتى 18 ساعة" },
  "Jusqu'a 10 h": { en: "Up to 10 h", ar: "حتى 10 ساعات" },
  "Circum-aural sans fil": { en: "Wireless over-ear", ar: "محيطي بالأذن لاسلكي" },
  "30 h avec ANC": { en: "30 h with ANC", ar: "30 ساعة مع عزل الضجيج" },
  "Active + audio adaptatif": { en: "Active + Adaptive Audio", ar: "نشط + صوت تكيّفي" },
  "6 h, 30 h avec le boitier": { en: "6 h, 30 h with the case", ar: "6 ساعات، 30 ساعة مع العلبة" },
  "24 h avec ANC": { en: "24 h with ANC", ar: "24 ساعة مع عزل الضجيج" },
  "Titane 49 mm": { en: "49 mm titanium", ar: "تيتانيوم 49 مم" },
  "Jusqu'a 40 m": { en: "Up to 40 m", ar: "حتى 40 مترًا" },
  "Jusqu'a 4K 120 Hz / 8K": { en: "Up to 4K 120 Hz / 8K", ar: "حتى 4K بتردد 120 هرتز / 8K" },
  "Port Ethernet integre": { en: "Built-in Ethernet port", ar: "منفذ Ethernet مدمج" },
  "4K natif jusqu'a 120 fps": { en: "Native 4K up to 120 fps", ar: "4K أصلية حتى 120 إطارًا" },
  "Lightspeed sans fil": { en: "Lightspeed wireless", ar: "Lightspeed لاسلكي" },
  "10 m sans caisson": { en: "10 m without a housing", ar: "10 أمتار دون علبة" },
  "Photo et video": { en: "Photo and video", ar: "تصوير وفيديو" },
  'Filetage 1/4" integre': { en: 'Built-in 1/4" thread', ar: "سنّ حلزوني ربع بوصة مدمج" },
  "3.5 avec Ray Reconstruction": {
    en: "3.5 with Ray Reconstruction",
    ar: "3.5 مع إعادة بناء الأشعة",
  },
  "Adaptatif par capteur": { en: "Adaptive, sensor-driven", ar: "تكيّفي عبر مستشعر" },
};
